package entity;
// Generated Jan 18, 2017 11:33:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProOrder generated by hbm2java
 */
public class ProOrder  implements java.io.Serializable {


     private Integer orderId;
     private DeliveryCost deliveryCost;
     private Product product;
     private ShopUser shopUser;
     private Date orderDate;
     private int orderQty;
     private double totalPrice;
     private String orderStatus;
     private Set proOrderDetailses = new HashSet(0);

    public ProOrder() {
    }

	
    public ProOrder(DeliveryCost deliveryCost, Product product, ShopUser shopUser, Date orderDate, int orderQty, double totalPrice, String orderStatus) {
        this.deliveryCost = deliveryCost;
        this.product = product;
        this.shopUser = shopUser;
        this.orderDate = orderDate;
        this.orderQty = orderQty;
        this.totalPrice = totalPrice;
        this.orderStatus = orderStatus;
    }
    public ProOrder(DeliveryCost deliveryCost, Product product, ShopUser shopUser, Date orderDate, int orderQty, double totalPrice, String orderStatus, Set proOrderDetailses) {
       this.deliveryCost = deliveryCost;
       this.product = product;
       this.shopUser = shopUser;
       this.orderDate = orderDate;
       this.orderQty = orderQty;
       this.totalPrice = totalPrice;
       this.orderStatus = orderStatus;
       this.proOrderDetailses = proOrderDetailses;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public DeliveryCost getDeliveryCost() {
        return this.deliveryCost;
    }
    
    public void setDeliveryCost(DeliveryCost deliveryCost) {
        this.deliveryCost = deliveryCost;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public ShopUser getShopUser() {
        return this.shopUser;
    }
    
    public void setShopUser(ShopUser shopUser) {
        this.shopUser = shopUser;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public int getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(int orderQty) {
        this.orderQty = orderQty;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Set getProOrderDetailses() {
        return this.proOrderDetailses;
    }
    
    public void setProOrderDetailses(Set proOrderDetailses) {
        this.proOrderDetailses = proOrderDetailses;
    }




}


