package entity;
// Generated Jan 18, 2017 11:33:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ShopUser generated by hbm2java
 */
public class ShopUser  implements java.io.Serializable {


     private Integer userId;
     private UserRole userRole;
     private String userName;
     private String password;
     private String email;
     private Date regDate;
     private String contactNo;
     private Set proOrders = new HashSet(0);

    public ShopUser() {
    }

	
    public ShopUser(UserRole userRole, String userName, String password, String email, Date regDate, String contactNo) {
        this.userRole = userRole;
        this.userName = userName;
        this.password = password;
        this.email = email;
        this.regDate = regDate;
        this.contactNo = contactNo;
    }
    public ShopUser(UserRole userRole, String userName, String password, String email, Date regDate, String contactNo, Set proOrders) {
       this.userRole = userRole;
       this.userName = userName;
       this.password = password;
       this.email = email;
       this.regDate = regDate;
       this.contactNo = contactNo;
       this.proOrders = proOrders;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public Set getProOrders() {
        return this.proOrders;
    }
    
    public void setProOrders(Set proOrders) {
        this.proOrders = proOrders;
    }




}


